export type EdealerVehicleCompareArray = Record<string, EdealerItemEntry>;

export interface EdealerItemEntry {
  vehicleId:                              string;
  edealerId:                              string;
  recommendedVehicles:                    null;
  soldBy:                                 string;
  user:                                   null;
  sellerName:                             string;
  dealerName:                             string;
  dealer:                                 null;
  dealerWebId:                            null;
  privateSeller:                          null;
  areaCode:                               string;
  phone1:                                 string;
  phone2:                                 string;
  address:                                string;
  cityWebId:                              null;
  city:                                   string;
  province:                               string;
  postalCode1:                            string;
  postalCode2:                            string;
  hstTax:                                 boolean;
  coordsStatus:                           null;
  latitude:                               string;
  longitude:                              string;
  dealerId:                               string;
  status:                                 string;
  category:                               null;
  vin:                                    string;
  showVin:                                null;
  stockNum:                               string;
  year:                                   string;
  make:                                   string;
  model:                                  string;
  modelExtended:                          string;
  trim:                                   string;
  trimOption:                             string;
  mfr_ext_colour:                         string;
  mfr_int_colour:                         string;
  fuel_economy_city:                      string;
  fuel_economy_hwy:                       string;
  bodyStyle:                              string;
  listingSubTitle:                        null;
  price:                                  number;
  pricePrevious:                          number;
  priceSetFrom:                           string;
  pricePreviousSetFrom:                   string;
  mileage:                                string;
  DefaultPackageCode:                     string;
  PackageECC:                             null;
  cabType:                                string;
  financingType:                          null;
  financingDownPayment:                   null;
  financingNumOfPayments:                 null;
  financingPaymentType:                   null;
  financingPayment:                       null;
  financingDescription:                   null;
  condition:                              string;
  exteriorColour:                         string;
  interiorColour:                         string;
  numOfDoors:                             string;
  numOfPassengers:                        string;
  transmission:                           string;
  driveTrain:                             string;
  engine:                                 string;
  numOfCylinders:                         string;
  fuelType:                               string;
  code:                                   string;
  financing:                              null;
  warranty:                               null;
  certified:                              string;
  etested:                                null;
  gmOptimum:                              null;
  description:                            string;
  features:                               string;
  standardFeatures:                       null;
  numberOfImages:                         string;
  mainImage:                              null;
  images:                                 Images;
  video:                                  string;
  bannerText:                             string;
  bannerSize:                             string;
  bannerColor:                            string;
  bannerAlignment:                        string;
  carProofId:                             string;
  delivered:                              boolean;
  deliveredDate:                          Date;
  lastModified:                           Date;
  additionDate:                           Date;
  financingTable:                         null;
  distance:                               null;
  payment_value:                          string;
  payment_interval:                       string;
  solrStatus:                             null;
  isDownPaymentPercentage:                null;
  downPaymentValue:                       null;
  PaymentsDisclaimer:                     null;
  featured:                               string;
  vehicleSolrPayment:                     null;
  payment_disclaimer_short:               string;
  msrp_price:                             number;
  IOM_MSRP_Override:                      string;
  IOM_Cash_Price:                         string;
  IOM_Discount:                           string;
  IOM_UpdatePayments:                     string;
  IOMCashStackableVal:                    string;
  IOMFinanceStackableVal:                 string;
  IOMLeaseStackableVal:                   string;
  OEMOptionCodes:                         null;
  AllowedMileage:                         string;
  MileageAllowanceType:                   null;
  ExcessKilometerCost:                    null;
  LeaseKilometerAllowanceThreshold:       null;
  Acode:                                  string;
  msrp:                                   number;
  freight:                                number;
  custom_msrp:                            number;
  VideoEmbedHTML:                         string;
  PromotionImageHTML:                     string;
  PromotionTextHTML:                      string;
  preowned:                               boolean;
  finance_term:                           null;
  finance_interest_rate:                  null;
  lease_term:                             null;
  lease_interest_rate:                    null;
  ExpectedDaysInInventory:                null;
  mazdaCustomModelsArray:                 string[];
  age:                                    string;
  demo:                                   string;
  asis:                                   string;
  privateSellerId:                        null;
  msrp_total:                             number;
  OriginalPrice:                          number;
  OriginalPreviousPrice:                  number;
  OriginalMSRP:                           number;
  additional_fees:                        number;
  package_msrp:                           number;
  package_name:                           string;
  package_description:                    string;
  PackageCode:                            string;
  demoVehicle:                            string;
  intransitVehicle:                       string;
  primary_dealer:                         string;
  payment_disclaimer_short_borrow:        string;
  isDownpaymentPercentage:                boolean;
  downPayment:                            string;
  payment_value_lease:                    string;
  payment_interval_lease:                 string;
  payment_disclaimer_short_lease:         string;
  payment_disclaimer_short_borrow_lease:  string;
  PaymentsDisclaimerLease:                null;
  isDownpaymentPercentageLease:           boolean;
  downPaymentLease:                       string;
  PromotionName:                          string;
  PromotionImage:                         string;
  ShowImageOn:                            string;
  ImageLocationOnVDP:                     string;
  SEOPageText:                            string;
  SEOTitleTag:                            string;
  SEOMetaDescription:                     string;
  model_code:                             string;
  BannerURL:                              string;
  OverlayImageRuleID:                     string;
  onlyFirstImageHasOverlay:               boolean;
  promo_banner_expiration:                Date;
  segmentId:                              string;
  firstImage:                             string;
  AdminFeeAdded:                          boolean;
  aTitleSettingsString:                   string[];
  aTitlePropertyMappings:                 ATitlePropertyMappings;
  detailUrl:                              string;
  PromotionImageWithinVehicleDescription: string;
}

interface ATitlePropertyMappings {
  "[Year]":          string;
  "[Make]":          string;
  "[Model]":         string;
  "[Trim]":          string;
  "[TrimOption]":    string;
  "[PackageName]":   string;
  "([PackageName])": string;
  "[PackageCode]":   string;
  "([PackageCode])": string;
  "[CabType]":       string;
  "[DriveTrain]":    string;
}

interface Images {
  dirFs:            DirFS;
  dirWs:            string;
  noImage:          NoImage;
  mainImage:        null;
  images:           { [key: string]: Image };
  adminToolNoImage: string;
}

enum DirFS {
  VarWWWInventory20SmartdealerCAHTMLContentVehicle = "/var/www/inventory20.smartdealer.ca/html/content/vehicle/",
}

interface Image {
  source:   string;
  id:       string;
  rank:     number;
  dirFs:    DirFS;
  dirWs:    string;
  noImage:  NoImage;
  fileName: string;
  s3status: number;
}

enum NoImage {
  NoImageJpg = "no_image.jpg",
}
