export interface WPResponse {
  filters:     any;
  all_filters: any;
  summary:     any;
  results:     WPResult[];
}

export interface WPResult {
  vehicle_id:               number;
  company_id:               number;
  trader_company_id:        string;
  vin:                      string;
  year:                     number;
  stock_number:             string;
  make:                     string;
  model:                    string;
  trim:                     string;
  additional_title:         string;
  body_style:               string;
  sale_class:               string;
  vehicle_class_en:         string;
  vehicle_class:            string;
  vehicle_class_lvl2:       string;
  vehicle_class_lvl3:       string;
  drive_train:              string;
  engine:                   string;
  fuel_type:                string;
  transmission:             string;
  exterior_color:           string;
  interior_color:           string;
  description:              string;
  cylinder:                 number;
  manu_exterior_color:      string;
  odometer:                 number;
  passenger:                number;
  doors:                    number;
  certified:                number;
  manu_program:             number;
  msrp:                     number;
  asking_price:             number;
  sale_price:               number;
  internet_price:           number;
  retail_price:             number;
  invoice_price:            number;
  wholesale_price:          number;
  sales_tax:                number;
  price_badge:              null;
  fuel_economy_city_km:     number | null;
  fuel_economy_highway_km:  number | null;
  fuel_economy_city_mpg:    number | null;
  fuel_economy_highway_mpg: number | null;
  horsepower:               number;
  demo:                     number;
  ad_id:                    string;
  is_npv:                   number;
  headline:                 string;
  hours:                    number;
  days_on_lot:              number;
  sale_expiry:              string;
  in_transit:               null;
  vdp_url:                  string;
  yt_url:                   string;
  finance_fee:              number;
  finance_monthly_pmt:      number;
  finance_biweekly_pmt:     number;
  finance_weekly_pmt:       number;
  lease_monthly_pmt:        number;
  lease_biweekly_pmt:       number;
  lease_weekly_pmt:         number;
  lowest_price:             number;
  highest_price:            number;
  sort_price:               number;
  has_images:               number;
  has_price:                number;
  initial_price:            number;
  final_price:              number;
  breakdown:                any[];
  lease:                    null;
  finance:                  object[];
  company_data:             WPCompanyData;
  image:                    any[];
}

export interface WPCompanyData {
  company_id:          number;
  trader_company_id:   string;
  company_name:        string;
  company_address:     string;
  company_city:        string;
  company_province:    string;
  company_country:     string;
  company_postal:      string;
  company_lat:         string;
  company_lng:         string;
  company_sales_phone: string;
  company_sales_email: string;
  company_adf_email:   null;
  company_web_address: string;
  special_vehicles:    number;
  vehicle_incentives:  number;
  tax_rate:            number;
  company_disabled:    number;
  fused_id:            null;
  platform_inclusion:  number;
  fb_page_id:          string;
}